### ISSUE TITLE
Currently assumes python is available on the path, install it instead

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fetch-through-merge-base#32]
The key is to use the `update-environment` and then the `python-path` output:

```yaml
    - uses: actions/setup-python@v5
      id: python
      with:
        python-version: "3.12"
        update-environment: false
    - id: foo
      run: |
         "${{ steps.python.outputs.python-path }}" ...
```
